apiVersion: v1
kind: Pod
metadata:
  name: nebula-lighthouse
spec:
  restartPolicy: Always
  containers:
  - name: lighthouse
    command:
    - "bin/sh"
    - "-c"
    - "echo \"$(hostname -i) nebula-lighthouse\" > /config/hosts ; cat /config/hosts >> /etc/hosts ; mkdir /dev/net ; mknod /dev/net/tun c 10 200 ; tar xvf config/nebula-linux-amd64.tar.gz ; /nebula -config /config/lighthouse-config"
    image: docker.io/niteeshkd/test-cc-ssh:v0
    resources:
      limits:
        cpu: "8"
    securityContext:
      privileged: true 
    volumeMounts:
    - mountPath: /config
      name: lighthouse-config
  - name: app
    command:
    - "bin/sh"
    - "-c"
    - "apk add htop bash iperf3 ; mount -t tmpfs none /tmp ; iperf3 -s -p 5201 & iperf3 -s -p 5202 & iperf3 -s -p 5203 & iperf3 -s -p 5204"
    image: public.ecr.aws/docker/library/alpine:latest    
    securityContext:
      privileged: true 
  volumes:
  - name: lighthouse-config                                            
    # mount /data/foo, but only if that directory already exists
    hostPath:
      path: /data/niteesh/nebula-test/nebula-config # directory location on host
      type: Directory # this field is optional
---
