apiVersion: v1
kind: Pod
metadata:
  name: kbs-client
spec:
#  runtimeClassName: kata-snp
  containers:
  - name: kbs-client
    image: quay.io/confidential-containers/kbs-client:latest
    imagePullPolicy: IfNotPresent
    command:
      - sleep
      - "360000"
    env:
      - name: RUST_LOG
        value:  none
