/var/home/core/kata_qemu_rhel9/opt/kata/bin/qemu-system-x86_64 \
--enable-kvm \
-cpu EPYC-v4,pmu=off \
-machine q35,accel=kvm,kernel_irqchip=split,confidential-guest-support=snp \
-smp 1,cores=1,threads=1,sockets=1,maxcpus=1 \
-m 2048M,slots=10,maxmem=770596M \
-no-reboot \
-vga none \
-daemonize \
-no-user-config -nodefaults -nographic \
-serial file:/var/home/core/qemu.log \
--trace "kvm_sev*" \
-D /var/home/core/qemu-trace.log \
-global isa-debugcon.iobase=0x402 \
-object memory-backend-ram,id=dimm1,size=2048M \
-numa node,memdev=dimm1 \
-object sev-snp-guest,id=snp,cbitpos=51,reduced-phys-bits=1,kernel-hashes=on \
-kernel /opt/kata/share/kata-containers/vmlinuz-confidential.container \
-bios /usr/share/edk2/ovmf/OVMF.amdsev.fd \
-device pci-bridge,bus=pcie.0,id=pci-bridge-0,chassis_nr=1,shpc=off,addr=2,romfile=,io-reserve=4k,mem-reserve=1m,pref64-reserve=1m \
-device virtio-serial-pci,disable-modern=false,id=serial0,romfile= \
-device virtconsole,chardev=charconsole0,id=console0 \
-chardev socket,id=charconsole0,path=/var/home/core/console.sock,server=on,wait=off \
-device virtio-scsi-pci,id=scsi0,disable-modern=false,romfile= \
-object rng-random,id=rng0,filename=/dev/urandom \
-device virtio-rng-pci,rng=rng0,romfile= \
-rtc base=utc,driftfix=slew,clock=host \
-global kvm-pit.lost_tick_policy=discard \
-append "tsc=reliable no_timer_check rcupdate.rcu_expedited=1 i8042.direct=1 i8042.dumbkbd=1 i8042.nopnp=1 i8042.noaux=1 noreplace-smp reboot=k cryptomgr.notests net.ifnames=0 pci=lastbus=0 console=hvc0 console=hvc1 debug panic=1 nr_cpus=1 selinux=0 scsi_mod.scan=none agent.log=debug agent.debug_console agent.debug_console_vport=1026 console=ttyS0" \
-initrd "/opt/kata/share/kata-containers/kata-containers-initrd-confidential.img" \
