apiVersion: v1
kind: Pod
metadata:
  labels:
    app: test-kata
  name: test-kata
  namespace: default
spec:
  runtimeClassName: kata
  containers:
  - args:
    - "20000"
    command:
    - sleep
    image: busybox:1.28
    imagePullPolicy: Always
    name: test
