---
apiVersion: v1
kind: Pod
metadata:
  name: pod1-lswan
spec:
  runtimeClassName: kata-qemu
  restartPolicy: Always
  containers:
  - name: p1c1
    command:
    - "/bin/bash"
    - "-c"
    - "apt -y update ; apt -y install libreswan iperf3 ; sleep infinity" 
    image: ubuntu
    resources:
      limits:
        cpu: "8"
    securityContext:
      privileged: true
    imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Pod
metadata:
  name: pod2-lswan
spec:
  runtimeClassName: kata-qemu
  restartPolicy: Always
  containers:
  - name: p2c1
    command:
    - "/bin/bash"
    - "-c"
    - "apt -y update ; apt -y install libreswan iperf3 ; sleep infinity" 
    image: ubuntu
    resources:
      limits:
        cpu: "8"
    securityContext:
      privileged: true
    imagePullPolicy: IfNotPresent
