---
apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  restartPolicy: Always
  containers:
  - name: p1c1
    command:
    - "/bin/bash"
    - "-c"
    - "apt -y update ; apt -y install systemd iperf3 ; sleep infinity" 
    image: ubuntu
    resources:
      limits:
        cpu: "8"
    securityContext:
      privileged: true
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - mountPath: /run/systemd/system
      name: systemd
    - mountPath: /var/run/dbus/system_bus_socket
      name: dbus
  volumes:
  - name: systemd
    hostPath:
      path: /run/systemd/system  # directory location on host
  - name: dbus
    hostPath:
      path: /var/run/dbus/system_bus_socket  # directory location on host
---
apiVersion: v1
kind: Pod
metadata:
  name: pod2
spec:
  restartPolicy: Always
  containers:
  - name: p2c1
    command:
    - "/bin/bash"
    - "-c"
    - "apt -y update ; apt -y install systemd iperf3 ; sleep infinity" 
    image: ubuntu
    resources:
      limits:
        cpu: "8"
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /run/systemd/system
      name: systemd
    - mountPath: /var/run/dbus/system_bus_socket
      name: dbus
    imagePullPolicy: IfNotPresent
  volumes:
  - name: systemd
    hostPath:
      path: /run/systemd/system  # directory location on host
  - name: dbus
    hostPath:
      path: /var/run/dbus/system_bus_socket  # directory location on host
